//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3053
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WudiStudio.Chestnut.Utilities {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang_zh_CN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang_zh_CN() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WudiStudio.Chestnut.Utilities.Lang_zh-CN", typeof(Lang_zh_CN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 词典的作者 的本地化字符串。
        /// </summary>
        internal static string argument_author {
            get {
                return ResourceManager.GetString("argument_author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 从指定文件生成词典 的本地化字符串。
        /// </summary>
        internal static string argument_build {
            get {
                return ResourceManager.GetString("argument_build", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检查指定文件是否是合法的词典 的本地化字符串。
        /// </summary>
        internal static string argument_check {
            get {
                return ResourceManager.GetString("argument_check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 处理 .NET 程序使用的词典 的本地化字符串。
        /// </summary>
        internal static string argument_dotnet {
            get {
                return ResourceManager.GetString("argument_dotnet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 English interface 的本地化字符串。
        /// </summary>
        internal static string argument_english {
            get {
                return ResourceManager.GetString("argument_english", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出词典中的所有词汇 的本地化字符串。
        /// </summary>
        internal static string argument_export {
            get {
                return ResourceManager.GetString("argument_export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 词汇文件列表，或词典文件 的本地化字符串。
        /// </summary>
        internal static string argument_files {
            get {
                return ResourceManager.GetString("argument_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 词典格式 (bin, php, dotnet) 的本地化字符串。
        /// </summary>
        internal static string argument_format {
            get {
                return ResourceManager.GetString("argument_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用 GBK 字符集 的本地化字符串。
        /// </summary>
        internal static string argument_gbk {
            get {
                return ResourceManager.GetString("argument_gbk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示此帮助信息 的本地化字符串。
        /// </summary>
        internal static string argument_help {
            get {
                return ResourceManager.GetString("argument_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示指定词典的元信息 的本地化字符串。
        /// </summary>
        internal static string argument_info {
            get {
                return ResourceManager.GetString("argument_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定输出文件文件名 的本地化字符串。
        /// </summary>
        internal static string argument_output {
            get {
                return ResourceManager.GetString("argument_output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 词典的标题 的本地化字符串。
        /// </summary>
        internal static string argument_title {
            get {
                return ResourceManager.GetString("argument_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 升级词典到版本二 的本地化字符串。
        /// </summary>
        internal static string argument_upgrade {
            get {
                return ResourceManager.GetString("argument_upgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完成。 的本地化字符串。
        /// </summary>
        internal static string completed {
            get {
                return ResourceManager.GetString("completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (C) 版权所有 2007 Wudi Studio 的本地化字符串。
        /// </summary>
        internal static string copyright {
            get {
                return ResourceManager.GetString("copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在反序列化 {0} ...  的本地化字符串。
        /// </summary>
        internal static string deserializing_x {
            get {
                return ResourceManager.GetString("deserializing_x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 命令: 的本地化字符串。
        /// </summary>
        internal static string help_commands {
            get {
                return ResourceManager.GetString("help_commands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选项: 的本地化字符串。
        /// </summary>
        internal static string help_options {
            get {
                return ResourceManager.GetString("help_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数: 的本地化字符串。
        /// </summary>
        internal static string help_params {
            get {
                return ResourceManager.GetString("help_params", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用法: 的本地化字符串。
        /// </summary>
        internal static string help_usage {
            get {
                return ResourceManager.GetString("help_usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已完成，写入了 {0:#,#} 项。 的本地化字符串。
        /// </summary>
        internal static string indexes_wrote {
            get {
                return ResourceManager.GetString("indexes_wrote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已完成，处理了 {0:#,#} 个节点。 的本地化字符串。
        /// </summary>
        internal static string nodes_processed {
            get {
                return ResourceManager.GetString("nodes_processed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按任意键继续... 的本地化字符串。
        /// </summary>
        internal static string press_any_key_to_exit {
            get {
                return ResourceManager.GetString("press_any_key_to_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在读取版本一词典 ... 的本地化字符串。
        /// </summary>
        internal static string reading_from_v1 {
            get {
                return ResourceManager.GetString("reading_from_v1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 直接读取版本二词典 ...  的本地化字符串。
        /// </summary>
        internal static string reading_from_v2 {
            get {
                return ResourceManager.GetString("reading_from_v2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在读取词汇 ...  的本地化字符串。
        /// </summary>
        internal static string reading_words {
            get {
                return ResourceManager.GetString("reading_words", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在读取 {0} ...  的本地化字符串。
        /// </summary>
        internal static string reading_x {
            get {
                return ResourceManager.GetString("reading_x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在序列化词典 ...  的本地化字符串。
        /// </summary>
        internal static string serializing_lexicon {
            get {
                return ResourceManager.GetString("serializing_lexicon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在序列化到 {0} ...  的本地化字符串。
        /// </summary>
        internal static string serializing_to_x {
            get {
                return ResourceManager.GetString("serializing_to_x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在排序词汇 ...  的本地化字符串。
        /// </summary>
        internal static string sorting_words {
            get {
                return ResourceManager.GetString("sorting_words", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生成数组 的本地化字符串。
        /// </summary>
        internal static string step_building_arrays {
            get {
                return ResourceManager.GetString("step_building_arrays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 处理节点 的本地化字符串。
        /// </summary>
        internal static string step_building_dicts {
            get {
                return ResourceManager.GetString("step_building_dicts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生成词典 的本地化字符串。
        /// </summary>
        internal static string step_building_lexicon {
            get {
                return ResourceManager.GetString("step_building_lexicon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生成 TRIE 树 的本地化字符串。
        /// </summary>
        internal static string step_building_tree {
            get {
                return ResourceManager.GetString("step_building_tree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 转换词典 的本地化字符串。
        /// </summary>
        internal static string step_converting_lexicon {
            get {
                return ResourceManager.GetString("step_converting_lexicon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [第 {0}/{1} 步] {2} 的本地化字符串。
        /// </summary>
        internal static string step_format {
            get {
                return ResourceManager.GetString("step_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [{0}/{1}] {2} ...  的本地化字符串。
        /// </summary>
        internal static string step_format_file {
            get {
                return ResourceManager.GetString("step_format_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取文件 的本地化字符串。
        /// </summary>
        internal static string step_reading_files {
            get {
                return ResourceManager.GetString("step_reading_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取词典 的本地化字符串。
        /// </summary>
        internal static string step_reading_lexicon {
            get {
                return ResourceManager.GetString("step_reading_lexicon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取词汇 的本地化字符串。
        /// </summary>
        internal static string step_reading_words {
            get {
                return ResourceManager.GetString("step_reading_words", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 写入词典 的本地化字符串。
        /// </summary>
        internal static string step_writing_lexicon {
            get {
                return ResourceManager.GetString("step_writing_lexicon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wudi&apos;s Lexicon Utilities 的本地化字符串。
        /// </summary>
        internal static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在反序列化 {0} ...  的本地化字符串。
        /// </summary>
        internal static string unserializing_x {
            get {
                return ResourceManager.GetString("unserializing_x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 命令 的本地化字符串。
        /// </summary>
        internal static string usage_command {
            get {
                return ResourceManager.GetString("usage_command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选项 的本地化字符串。
        /// </summary>
        internal static string usage_options {
            get {
                return ResourceManager.GetString("usage_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已完成，添加了 {0:#,#} 个词汇。 的本地化字符串。
        /// </summary>
        internal static string words_added {
            get {
                return ResourceManager.GetString("words_added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0:#,#} 个词汇已读取。 的本地化字符串。
        /// </summary>
        internal static string words_read {
            get {
                return ResourceManager.GetString("words_read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在写入词典 ...  的本地化字符串。
        /// </summary>
        internal static string writing_lexicon {
            get {
                return ResourceManager.GetString("writing_lexicon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在写入词汇 ...  的本地化字符串。
        /// </summary>
        internal static string writing_words {
            get {
                return ResourceManager.GetString("writing_words", resourceCulture);
            }
        }
    }
}
